# Generated by Django 3.2.7 on 2021-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='short_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=201)),
                ('long_url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
